export const quiz_main = {
    totalQuestions: 26,
    questions: [
      {
        id: 1,
        question: 'You ponder over setting aside money for unforeseen events. Do you:',
        answers: ['Decide not to set aside any specific funds for emergencies, choosing to deal with situations as they arise',
                  'Allocate a small amount to start an emergency fund, adding to it when possible',
                  'Commit to saving a more significant amount for your emergency fund and hope it last until the end of the year',
                  'Set up a regular savings plan, consistently dedicating a portion of your income each month to build and maintain your emergency fund'],  
        correctAnswer: [1,2,3,4],
        monthlyAdd: [0,0,0,0],
        checkingCharge: [0,0,0,0],
        checkingChargeOneTime: [0,300,1000,100],
        checkingAdd: [0,0,0,0],
        savingsCharge: [0,-300,-1000,-100],
        newMonth: false,
        factor: "Planning",
        month: "August"
      },
      {
        id: 2,
        question: 'You received an ‘approved application’ for a credit card with good cash back rewards and benefits but with an interest rate of 18%. Do you:',
        answers: ['Apply regardless of your knowledge about what the interest rate implies',
            'Look up how interest rates work before getting one',
            'Decide against it, knowing high-interest rates can be costly',
            'Compare with other credit cards to find a lower rate'],
        correctAnswer: [2,1,3,4],
        monthlyAdd: [0,0,0,0],
        checkingCharge: [0,0,0,0],
        checkingChargeOneTime: [50,40,0,75],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Knowledge",
        month: "August"
      },
      {
        id: 3,
        question: 'Noticing that everyone around you is using high-end smartphones, do you:',
        answers: ['Keep using your current phone, avoiding extra expenses',
            'Opt for a modest upgrade to fit in, without going overboard',
            'Decide to get the latest model to match your peers',
            'Find a compromise with a used or refurbished newer model'],
        correctAnswer: [1,3,4,2],
        monthlyAdd: [0,-30,-45,-20],
        savingsCharge: [0,0,0,0],
        newMonth: true,
        factor: "Influence",
        month: "September"
      },
      {
        id: 4,
        question: 'After a particularly tough week at work, you feel the urge to unwind. Do you:',
        answers: ['Treat yourself to an expensive night out or shopping spree',
            'Buy something small to cheer yourself up',
            'Engage in low-cost relaxation activities like a movie night at home',
            'Stick to your regular routine despite the stress'],
        correctAnswer: [1,2,3,4],
        monthlyAdd: [0,0,0,0],
        checkingCharge: [0,0,0,0],
        checkingChargeOneTime: [150,50,15,0],
        savingsCharge: [0,0,0,0],
        newMonth: true,
        factor: "Feeling",
        month: "October"
      },
      {
        id: 5,
        question: 'Your job offers multiple retirement plans where you contribution will be matched by them, do you:',
        answers: ['Spend time learning about retirement funds in order to take a more aggressive approach',
            'Forgo starting a retirement fund for now',
            'Begin contributing whatever small amount you can spare now to a retirement fund',
            'Plan to consistently contribute a fixed, manageable amount to a retirement fund'],
        correctAnswer: [2,3,4,1],
        monthlyAdd: [-68,0,-25,-40],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Planning",
        month: "October"
      },
      {
        id: 6,
        question: ' Weighing risk and reward, you decide whether to invest in the stock market. Do you:',
        answers: ['Choose not to invest in the stock market',
            'Opt for a low-risk investment strategy',
            'Select a moderate-risk investment approach, accepting variable returns',
            'Decide on a high-risk investment plan, understanding it could yield high returns or significant losses'],
        correctAnswer: [1,2,3,4],
        monthlyAdd: [0,50,70,100],
        checkingChargeOneTime: [0,50,70,100],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Risk Tolerance",
        month: "October"
      },
      {
        id: 7,
        question: 'Faced with a tempting sale event, you decide how to act. Do you:',
        answers: ['Resist the temptation and do not make any purchase',
            "Make a purchase only if it's something you need, despite the sale",
            'Set a budget for the sale and stick to it, allowing some indulgence',
            'Make multiple purchases, swayed by the sale prices'],
        correctAnswer: [4,3,2,1],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [0,30,70,200],
        savingsCharge: [0,0,0,0],
        newMonth: true,
        factor: "Spending Habits",
        month: "November"
      },
      {
        id: 8,
        question: "With some extra money on hand, you're thinking about the best way to save it. Do you:",
        answers: ['Deposit it in a regular savings account for safety, easy access, and to earn interest',
            'Research or ask someone for advice on smarter ways to save, like a high-yield savings account',
            'Keep the money at home, in a place like a piggy bank or a hidden spot',
            'Decide to use it for something you need or have been saving up for'],
        correctAnswer: [4,3,1,2],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [0,0,0,0],
        savingsCharge: [-500,-500,0,0],
        newMonth: true,
        factor: "Knowledge",
        month: "December"
      },
      {
        id: 9,
        question: "Your friend group is organizing a white elephant gift exchange for the holidays, do you:",
        answers: ['Purchase an expensive or highly sought-after gift to impress your peers',
            'Select a meaningful gift that fits within a modest budget',
            'Choose a humorous or low-cost item, prioritizing participation over gift value',
            'Decide not to participate in the gift exchange, preferring to avoid the expense'],
        correctAnswer: [4,3,2,1],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [100,50,20,0],
        savingsCharge: [0,0,0,0],
        newMonth: true,
        factor: "Influence",
        month: "December"
      },
      {
        id: 10,
        question: "At the end of the year, you review your bank account and notice it's lower than you expected. Do you:",
        answers: ['Become concerned about your finances and immediately start planning a stricter budget or look for ways to increase your income',
            "Experience slight worry, but don't take any immediate action, hoping things will naturally improve",
            'See consistent fluctuations in finances as a typical part of life',
            'Remain not overly concerned now but plan to adjust your spending or saving habits in the future to avoid a repeat   '],
        correctAnswer: [1,2,3,4],
        monthlyAdd: [0,0,0,0],
        checkingCharge: [0,0,0,0],
        checkingChargeOneTime: [0,0,0,0],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Feeling",
        month: "December"
      },
      {
        id: 11,
        question: "As the new year begins, you're readjusting your budget for the new year. Do you:",
        answers: ['utilize coupons at grocery stores and restaurants',
            'Start buying in bulk at the grocery store',
            'Remain the same',
            'Start using a food delivery service'],
        correctAnswer: [4,3,2,1],
        monthlyAdd: [-75,-50,0,50],
        checkingChargeOneTime: [0,0,0,0],
        savingsCharge: [0,0,0,0],
        newMonth: true,
        factor: "Planning",
        month: "January"
      },
      {
        id: 12,
        question: 'The stock market experiences a significant drop. Do you:',
        answers: ['Decide to sell the investments you have to avoid further loss',
            'Keep your current investments, believing the market will recover',
            'See this as an opportunity to invest, taking advantage of the lower prices',
            'Not have any investments and choose to continue to not participate'],
        correctAnswer: [2,4,3,1],
        monthlyAdd: [-50,0,200,0],
        checkingChargeOneTime: [-50,0,200,0],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Risk Tolerance",
        month: "January"
      },
      {
        id: 13,
        question: "You're out shopping and come across an item you like but don't necessarily need. You decide to buy it. Reflecting on this purchase the next week, do you:",
        answers: ['Feel pleased with your purchase, believing it was worth the joy it brings',
            'Regret the decision, feeling it was an unnecessary expense and return it',
            "Feel neutral about the purchase; it doesn't significantly impact you either way",
            'Feel concerned about the financial implications of such impulsive purchases'],
        correctAnswer: [3,1,4,2],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [50,0,50,50],
        savingsCharge: [0,0,0,0],
        newMonth: true,
        factor: "Feeling",
        month: "February"
      },
      {
        id: 14,
        question: 'Your frugal family members have always emphasized thoughtful spending, especially when it comes to significant purchases. With this in mind, you consider buying an important and costly item, do you:',
        answers: ["Take into account your family's emphasis on budgeting, carefully saving and planning before making the purchase",
            'Consult with your family first, seeking their approval or advice before proceeding',
            'Try to balance your family’s principles with your personal needs and context, such as opting for cost-effective alternatives or investing in quality for long-term benefits',
            "Value your family's perspective, but make your own decision based on your research and preferences"],
        correctAnswer: [ 2,3,4,1],
        monthlyAdd: [-30,0,-30,-150],
        checkingChargeOneTime: [0,0,150,0],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Influence",
        month: "February"
      },
      {
        id: 15,
        question: "It's tax season, in line with your work/financial situation, do you:",
        answers: ["Ignore it, unsure of how to file taxes/if you're applicable",
            'Use a free online service to file your taxes.',
            'Research potential tax deductions to take advantage of',
            'Seek help from a tax professional or a financial counseling center at school'],
        correctAnswer: [1,3,4,2],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [500,-400,-600,-500],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Knowledge",
        month: "February"
      },
      {
        id: 16,
        question: 'At the start of the month, you receive a delayed $400 holiday bonus. Do you:',
        answers: ['Immediately divide your money into categories like rent, food, savings, and entertainment',
            "Make a few unplanned purchases first, then think about budgeting what's left",
            'Keep an eye on your bank balance throughout the month, making adjustments to your spending as needed',
            'Consult with a friend, family member, or use an app for advice on how best to allocate your funds'],
        correctAnswer: [4,1,2,3],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [-300,-250,-400,-200],
        savingsCharge: [-100,0,0,-200],
        newMonth: true,
        factor: "Planning",
        month: "March"
      },
      {
        id: 17,
        question: 'You come across a sale for a high-end brand you like. Do you:',
        answers: ['Purchase multiple expensive items on a whim',
            'Buy one item you’ve been wanting for a while',
            'Look but ultimately decide not to buy',
            'Ignore the sale, focusing on saving money'],
        correctAnswer: [2,3,4,1],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [250,60,0,0],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Spending Habits",
        month: "March"
      },
      {
        id: 18,
        question: 'When you think about the importance of saving for the long term such as buying a house and retirement, Do you:',
        answers: ['Feel worried about the future but respond by starting to research and plan',
            'Feel optimistic about the future and decide to start saving for the future after achieving certain milestones, like securing a full-time job',
            'Feel confident and are already taking steps, however small, towards retirement savings',
            'Get overwhelmed by the thought of retirement savings, choosing to focus on your current financial needs and obligations first'],
        correctAnswer: [2,3,4,1],
        monthlyAdd: [0,0,0,0],
        checkingCharge: [0,0,0,0],
        checkingChargeOneTime: [0,0,0,0],
        savingsCharge: [0,0,0,0],
        newMonth: true,
        factor: "Feeling",
        month: "April"
      },
      {
        id: 19,
        question: 'Your favorite influencer starts promoting a new lifestyle product, claiming it has significantly improved their daily routine. Do you:',
        answers: ['Decide to purchase the whole product kit right away, influenced by their recommendation',
            'First look up more information and reviews about the product before buying, intrigued by their endorsement',
            'Remain skeptical of influencer promotions and prefer to rely on your own research or trusted sources when considering new products',
            'Generally disregard influencer promotions, viewing them as more about advertising revenue than genuine advice'],
        correctAnswer: [4,3,2,1],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [100,80,0,0],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Influence",
        month: "April"
      },
      {
        id: 20,
        question: 'Your student loan repayment pause has ended and you must start paying $180/month, along with your budget to adhere to. Do you:',
        answers: ['Allocate a significant part of your budget to pay off the debt quickly, even if it means cutting back on other expenses',
            'Divide your budget to manage both debt payments and other living expenses, aiming for a steady but manageable repayment plan',
            'Make the minimum required payments on your debts, focusing more on maintaining your current lifestyle and budget',
            'Consult with a financial advisor or utilize budgeting tools to find the best strategy for managing your debt and budget simultaneously'],
        correctAnswer: [4,2,1,3],
        monthlyAdd: [-200,-100,-50,-150],
        checkingChargeOneTime: [0,0,0,0],
        savingsCharge: [0,0,0,0],
        newMonth: true,
        factor: "Spending Habits",
        month: "May"
      },
      {
        id: 21,
        question: "As May ends, you're planning your summer, which could include travel, work, or other activities. Do you:",
        answers: ['Prioritize saving part of your current income and using existing savings specifically for a summer travel plan',
            'Plan to work over the summer, focusing on saving and earning rather than spending on travel',
            'Revise your budget to balance work, essential expenses with some affordable leisure activities, possibly including a small trip',
            'Look for short-term projects or gigs on top of your current work to fund a modest summer travel experience or other activities'],
        correctAnswer: [3,1,4,2],
        monthlyAdd: [-150,0,0,0],
        checkingChargeOneTime: [0,0,500,0],
        savingsCharge: [500,0,0,0],
        newMonth: false,
        factor: "Planning",
        month: "May"
      },
      {
        id: 22,
        question: 'You come up with an exciting idea for a startup. With some extra time over the summer, do you:',
        answers: ['Decide to invest a portion of your savings and risk job security to fully commit your summer to developing the startup',
            'Look for external investors or consider a small loan to fund the startup while minimizing your personal financial risk',
            'Start working on your idea as a low-cost side project, balancing it with your job and other commitments',
            'Decide to wait, considering it too risky or time-consuming to pursue during this time'],
        correctAnswer: [4,3,2,1],
        monthlyAdd: [0,0,-150,0],
        checkingChargeOneTime: [0,0,0,0],
        savingsCharge: [1000,225,0,0],
        newMonth: true,
        factor: "Risk Tolerance",
        month: "June"
      },
      {
        id: 23,
        question: 'You see a free online course on personal finance management. Do you:',
        answers: ['Decide not to sign up, feeling that personal finance courses aren’t compelling or necessary for you',
            'Enroll with the intention of casually going through the course when you have time, mainly to pick up some basic concepts',
            'Enroll and actively participate in all aspects of the course, eager to improve your financial knowledge and skills',
            'Enroll with good intentions but find it hard to keep up with the course, eventually falling behind or not completing it'],
        correctAnswer: [1,3,4,2],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [0,0,0,0],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Knowledge",
        month: "June"
      },
      {
        id: 24,
        question: "You're tempted by a new gadget. Considering your current financial priorities, do you:",
        answers: ["Choose to buy the gadget immediately, feeling it's worth the immediate satisfaction",
            'Decide to save up for the gadget, setting aside a little money each month until you can afford it without financial strain',
            'Consider your current financial obligations and decide to prioritize necessities, delaying the gadget purchase',
            'Try to find a balance and buy a less expensive/used version'],
        correctAnswer: [1,3,4,2],
        monthlyAdd: [0,-50,0,0],
        checkingChargeOneTime: [200,0,0,120],
        savingsCharge: [0,0,0,0],
        newMonth: false,
        factor: "Feeling",
        month: "June"
      },
      {
        id: 25,
        question: 'As you face growing financial opportunities and responsibilities, you attempt to plan how to manage your finances in the upcoming year? Do you:',
        answers: ['Decide to handle your finances on your own, possibly using online resources and personal research',
            'Turn to knowledgeable friends or family for informal guidance and tips',
            'Opt for professional advice by consulting with a financial advisor to help navigate your financial growth',
            'Plan to enroll in a financial planning course next semester to gain structured knowledge and skills for better financial management'],
        correctAnswer: [1,3,4,2],
        monthlyAdd: [0,0,0,0],
        checkingChargeOneTime: [0,0,0,0],
        savingsCharge: [0,0,0,0],
        newMonth: true,
        factor: "Influence",
        month: "July"
      },
      {
        id: 26,
        question: "You’ve just received your last paycheck before fall, Do you:",
        answers: ['Choose to use a significant portion of it for end-of-summer activities and purchases',
            'Divide the paycheck, putting part into savings, spending the rest on current debts, needs, or leisure',
            'Prioritize saving most or all of the paycheck to cushion your budget for the rest of the year',
            'Allocate the paycheck towards clearing any debts or pending expenses you have accumulated over the summer, save the rest'],
        correctAnswer: [1,2,4,3],
        monthlyAdd: [0,0,0,0],
        checkingCharge: [0,0,0,0],
        checkingChargeOneTime: [500,100,500,0],
        savingsCharge: [0,-100,-500,0],
        newMonth: false,
        factor: "Spending Habits",
        month: "July"
      },      
    ],
  };
  